---
name: "Create new version tag"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: release
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Merge changes from main
        run: |
          git merge origin/main
      - name: Run tests and adjust version
        run: |
          mvn clean package
          mvn versions:set -DnewVersion=${{ inputs.version }}
          mvn versions:commit
      - name: Create tag, commit and push
        run: |
          git add .
          git commit -m "Create version v${{ inputs.version }}"
          git tag v${{ inputs.version }}
          git push origin release
          git push origin v${{ inputs.version }}